apiVersion: v2
name: kubernetes-graphql
description: A chart for GraphQL API server of Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 0.1.15
keywords:
  - graphql
  - mesh
home: https://onelittlenightmusic.github.io/kubernetes-graphql/helm-chart
sources:
  - https://github.com/onelittlenightmusic/kubernetes-graphql
dependencies:
  - name: graphql-mesh
    version: 0.1.0
    repository: https://onelittlenightmusic.github.io/graphql-mesh-docker/helm-chart
    tags: # (optional)
      - mesh
    enabled: true
  - name: kubernetes-api-proxy
    version: 0.1.0
    enabled: true
maintainers: # (optional)
  - name: Hiro OSAKI
    url: https://github.com/onelittlenightmusic
# icon: A URL to an SVG or PNG image to be used as an icon (optional).
deprecated: false
