apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  generation: 1
  name: my-kubernetes-graphql
  namespace: default
spec:
  rules:
  - host: graphql-mesh-k8s.127.0.0.1.xip.io
    http:
      paths:
      - backend:
          service:
            name: mesh-svc
            port:
              number: 4000
        path: /
        pathType: Prefix