apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mesh
  name: mesh
  namespace: default
spec:
  containers:
  - image: hiroyukiosaki/graphql-mesh:latest-all-alpine
    name: mesh
    stdin: true 
    tty: true 
    resources: {}
    ports:
    - containerPort: 4000
    # - containerPort: 3999
    volumeMounts:
    - mountPath: /work/.meshrc.yaml
      name: meshrc-cm
      subPath: .meshrc.yaml
    - mountPath: /work/init.sh
      name: meshrc-cm
      subPath: init.sh
    - mountPath: /work/example-query.graphql
      name: meshrc-cm
      subPath: example-query.graphql
    - mountPath: /work/additional-resolvers.js
      name: meshrc-cm
      subPath: additional-resolvers.js
    # command:
    # - sh
    # - -c
    # - sleep 3600
  - image: hiroyukiosaki/openapi-to-graphql:latest
    name: otg
    stdin: true 
    tty: true 
    command:
    - sh
    - initOtg.sh
    volumeMounts:
    - mountPath: /initOtg.sh
      name: meshrc-cm
      subPath: initOtg.sh
    ports:
    - containerPort: 3000
  - image: bitnami/kubectl:latest
    name: proxy
    ports:
    - containerPort: 8001
    command:
    - /bin/bash
    - -c
    - kubectl proxy --address 0.0.0.0 --accept-hosts='.*'
  volumes:
  - name: meshrc-cm
    configMap:
      name: meshrc-cm
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  serviceAccountName: mesh
status: {}
